# This file is for Skaffold
# Skaffold handles the workflow for building, pushing and deploying your application in K8s

apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl: 
    # all the k8s yaml depl files are in this directory, watch these and apply (k apply -f .)
    # CRUD depl files on start and end
    manifests:
      - ./infra/k8s/*
build:
  # should images be pushed to a registry. If not specified, images are pushed only if the current Kubernetes context connects to a remote cluster.
    # local:
    #   push: false
    googleCloudBuild:
      projectId: ticketing-dev-301615
    artifacts:
      # name of the image to be built.
      # for google cloud build, image name always follow this format us.gcr.io/projectId/
      - image: us.gcr.io/ticketing-dev-301615/auth
      # directory containing the artifact's sources.
        context: auth
        docker: 
          dockerfile: Dockerfile
        sync:
      # we want to match all js files in our clients directory, unless we are adding new dependencies, all js file changes are just copied instead of rebuilding the docker image
          manual:
            - src: 'src/**/*.ts'
      # Take wherever the file was found and place it right back 
              dest: .
